// Numerical-hardening initiative, section 8: pairwise mode coverage,
// sub-model A (Pro estimate). Generated by docs/generate_pairwise_cases.js
// -- see tests/pairwise/generated-cases.json for the raw covering array and
// PAIRWISE_COVERAGE_REPORT.md for the methodology and coverage proof.
//
// Each case exercises a real, distinct combination of surface/geometry/
// pricing modes through the actual production pipeline
// (assembleProjectEstimate), asserting the case-appropriate calculation
// state and, for priced cases, the requested price status is genuinely
// reached (not merely that nothing crashed) -- catching mode-INTERACTION
// bugs, which is what pairwise testing is for. Per-case numeric precision
// is already exhaustively covered by the 205,000-fixture differential
// suite and the 257,000-comparison property suite; this suite's job is
// combinatorial coverage, not re-deriving exact cents for every case.
import { describe, it, expect } from 'vitest';
import generated from './generated-cases.json';
import { sequentialIdSource } from '../../src/domain/ids';
import { createSnapshot } from '../../src/domain/snapshot';
import { createDraftRevision } from '../../src/domain/project';
import { assembleProjectEstimate } from '../../src/domain/estimateAssembly';
import type { BusinessSettings, PaintVariant, Room, Surface, EstimateRevision } from '../../src/domain/entities';

const NOW = '2026-01-01T00:00:00.000Z';

const WASTE_BAND: Record<string, string> = { zero: '0', normal: '0.10', highWarn: '0.6', max: '1' };
const OVERHEAD_BAND: Record<string, string> = { zero: '0', normal: '0.15', highWarn: '0.6', max: '1' };
const TARGET_BAND: Record<string, string> = { zero: '0', normal: '0.35', nearMax: '0.999' };

function settings(overheadRatio: string, targetMarginRatio: string): BusinessSettings {
  return {
    id: 's1', loadedHourlyRate: '32', overheadRatio, targetMarginRatio, defaultCoats: 2, defaultWasteRatio: '0.10',
    wallThroughput: '150', ceilingThroughput: '120', trimThroughput: '40', doorHoursPerSidePerCoat: '0.75', defaultTravelAmount: '0',
    defaultSuppliesAllowance: { mode: 'none', amount: '0', ratio: '0' }, sampleAssumptionsConfirmed: true, createdAt: NOW, updatedAt: NOW,
  };
}
function variant(): PaintVariant {
  return { id: 'paint-1', name: 'White', color: 'white', sheen: 'eggshell', pricePerGal: '42', coverageFt2PerGal: '350', purchaseIncrementGal: '1', createdAt: NOW, updatedAt: NOW };
}

type Case = (typeof generated.subModels.A_proEstimate.generatedCases)[number];

function buildRevision(c: Case): EstimateRevision {
  const ids = sequentialIdSource();
  const bSettings = settings(OVERHEAD_BAND[c.overheadBand], TARGET_BAND[c.targetMarginBand]);
  const snap = createSnapshot(bSettings, [variant()], [], ids, 'rev-1');
  let revision = createDraftRevision('project-1', snap, ids);

  const throughputByKind: Record<string, string> = { wall: '150', ceiling: '120', trim: '40' };
  const laborRate = c.laborRateSource === 'surfaceOverride' ? '45' : null;
  const throughput = c.surfaceType !== 'door' && c.throughputSource === 'surfaceOverride' ? '200' : null;
  const hoursPerSidePerCoat = c.surfaceType === 'door' && c.throughputSource === 'surfaceOverride' ? '1.0' : null;

  const rooms: Room[] = [];
  const surfaces: Surface[] = [];

  const usesRoom = (c.surfaceType === 'wall' || c.surfaceType === 'ceiling') && c.measurementMode === 'roomDerived';
  if (usesRoom) {
    rooms.push({
      id: 'room-1', name: 'Room', lengthFt: '20', widthFt: '16', heightFt: '9',
      deductionEnabled: c.openingMode === 'detailed', openingMode: c.openingMode as 'quick' | 'detailed',
      quick: { doorCount: 1, windowCount: 1, doorAreaEach: '20', windowAreaEach: '15' },
      openings: c.openingMode === 'detailed' ? [{ id: 'op-1', type: 'door', widthFt: '3', heightFt: '7', count: 1 }] : [],
      surfaceIds: ['surface-1'],
    });
  }

  const base = {
    id: 'surface-1', roomId: usesRoom ? 'room-1' : null, enabled: true,
    paintVariantId: 'paint-1', coats: c.coats, wasteRatio: WASTE_BAND[c.wasteBand],
    loadedHourlyRate: laborRate, throughput, hoursPerSidePerCoat,
  };
  if (c.surfaceType === 'wall' || c.surfaceType === 'ceiling') {
    surfaces.push({
      ...base, kind: c.surfaceType, measurementMode: c.measurementMode as 'manual' | 'roomDerived',
      areaFt2: c.measurementMode === 'manual' ? '400' : null,
      trimLengthFt: null, developedWidthFt: null, doorCount: null, widthFt: null, heightFt: null, paintedSides: null,
    });
  } else if (c.surfaceType === 'trim') {
    surfaces.push({
      ...base, kind: 'trim', measurementMode: 'manual', areaFt2: null,
      trimLengthFt: '100', developedWidthFt: '0.5', doorCount: null, widthFt: null, heightFt: null, paintedSides: null,
    });
  } else {
    surfaces.push({
      ...base, kind: 'door', measurementMode: 'manual', areaFt2: null, trimLengthFt: null, developedWidthFt: null,
      doorCount: 2, widthFt: '3', heightFt: '7', paintedSides: 1,
    });
  }

  const suppliesAllowance =
    c.suppliesMode === 'none' ? { mode: 'none' as const, amount: '0', ratio: '0' } :
    c.suppliesMode === 'flat' ? { mode: 'flat' as const, amount: '50', ratio: '0' } :
    { mode: 'paintPercent' as const, amount: '0', ratio: '0.1' };

  revision = { ...revision, rooms, surfaces, suppliesAllowance };
  return revision;
}

describe('PAIRWISE-A: Pro estimate mode-interaction coverage', () => {
  const cases = generated.subModels.A_proEstimate.generatedCases as Case[];

  it.each(cases.map((c, i) => [i, c] as const))('case %i: %o', (_i, c) => {
    const revision = buildRevision(c);

    // Pass 1: discover the raw cost with no price entered.
    const discovery = assembleProjectEstimate(revision, { priceMode: 'custom', customPriceRaw: '' });
    expect(['complete', 'invalid']).toContain(discovery.calculationState);
    if (discovery.calculationState !== 'complete') {
      // Some combinations at the extreme bands (waste=1, overhead=1) can
      // legitimately trip AGG-* aggregate ceilings -- that is itself a
      // valid, correctly-reported outcome, not a test failure.
      expect(discovery.outOfSupportedRange || discovery.reasons.length > 0).toBe(true);
      return;
    }
    const jobCost = discovery.jobCost!;
    const minTarget = discovery.price!.minimumTargetPrice!;
    expect(jobCost.isFinite()).toBe(true);
    expect(minTarget.isFinite()).toBe(true);

    let priceOptions: { priceMode: 'suggested' | 'custom'; customPriceRaw: string };
    if (c.priceMode === 'suggested') {
      priceOptions = { priceMode: 'suggested', customPriceRaw: '' };
    } else {
      const entered = {
        unpriced: null,
        zeroPrice: '0',
        belowCost: jobCost.times('0.5').toFixed(2),
        // minimumTargetPrice is itself a CEILING to whole cents (it must
        // guarantee AT LEAST the target margin), so one cent below it is
        // reliably strictly below target regardless of the case's cost
        // scale.
        belowTarget: minTarget.minus('0.01').toFixed(2),
        atTarget: minTarget.toFixed(2),
        aboveTarget: minTarget.times('1.5').toFixed(2),
      }[c.priceState];
      priceOptions = { priceMode: 'custom', customPriceRaw: entered ?? '' };
    }

    const final = assembleProjectEstimate(revision, priceOptions);
    expect(final.calculationState).toBe('complete');
    expect(final.jobCost!.isFinite()).toBe(true);
    expect(final.jobCost!.isNegative()).toBe(false);

    if (c.priceMode === 'suggested') {
      // minimumTargetPrice CEILs to the nearest cent that guarantees at
      // least the target margin -- when the exact required price isn't
      // already a whole cent, the suggested price's real margin lands a
      // hair above target, not exactly at it. Both are correct; which one
      // occurs is a data-dependent rounding fact, not a mode this test
      // controls.
      expect(['at_target', 'above_target']).toContain(final.price!.status);
    } else if (c.priceState === 'unpriced') {
      expect(final.price!.status).toBe('unpriced');
    } else if (c.priceState === 'atTarget') {
      // Same ceiling-rounding fact as above applies to an entered price
      // set to exactly minimumTargetPrice.
      expect(['at_target', 'above_target']).toContain(final.price!.status);
    } else if (c.priceState === 'belowTarget' && minTarget.minus(jobCost).lessThan('0.02')) {
      // Degenerate at targetMarginBand='zero': minimumTargetPrice is then
      // approximately equal to cost itself, so there is no real "below
      // target but above cost" price band to land in -- one cent below the
      // target price falls below cost instead. This is an inherent domain
      // fact (a zero target margin means "at cost" already satisfies the
      // target), not a bug; either status is a correct outcome here.
      expect(['below_cost', 'below_target']).toContain(final.price!.status);
    } else {
      const statusMap: Record<string, string> = {
        zeroPrice: 'zero_price', belowCost: 'below_cost', belowTarget: 'below_target', aboveTarget: 'above_target',
      };
      expect(final.price!.status).toBe(statusMap[c.priceState]);
    }
    // No result field ever displays a non-finite or negative-zero value,
    // regardless of which mode combination produced it.
    for (const field of [final.materials, final.laborCost, final.directCost, final.overhead, final.jobCost] as const) {
      if (field) {
        expect(field.isFinite()).toBe(true);
        expect(field.isNegative()).toBe(false);
      }
    }
  });
});
